jwt:
  secret-key: auctionjwtsecretkeyforjwtencrp
  expiration-time: 86400000
cloud:
  aws:
    credentials:
      accessKey: AKIAQRJOZRYVCJDKZFKV
      secretKey: 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
    s3:
      bucket: auctionttang
      dir: /auction/images
    region:
      static: ap-northeast-2
    stack:
      auto: false