spring:
  application:
    name: programmers spring assignments
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test_db;MODE=MYSQL;DB_CLOSE_DELAY=-1;NON_KEYWORDS=USER
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  profiles:
    active:
      - secret
